### create category
POST localhost:8888/category/boyadzhia%0A
Content-Type: application/json

{
}

### delete category
DELETE localhost:8888/category/asdf
Content-Type: application/json

{
}

### get all
GET localhost:8888/category/all