### add
POST localhost:8888/comments
Content-Type: application/json

{
"text" : "comment"
}

### register
POST localhost:8888/user
Content-Type: application/json

{
  "email" : "marto2@abv.bg",
  "password" : "m1235",
  "confirmPassword": "m1235",
  "firstName": "Marto",
  "lastName": "Ivanov",
  "phoneNumber": "0812312345"
}