### addComment
POST localhost:8888/4/comments
Content-Type: application/json

{
"text" : "comment2"
}

### getComment
GET localhost:8888/comments/4
Content-Type: application/json




@GetMapping("comment/{id}/delete")
public CommentDTO deleteById(@PathVariable int id,HttpSession session,HttpServletRequest request){
UserUtility.validateLogin(session,request);
Comment comment = commentService.getComment(id);
commentService.deleteById();
}