### create post
POST localhost:8888/post/
Content-Type: application/json

{
"categoryName" : "boyadzhia",
"description" : "Mnogo boyadisvam",
"cityName" : "sofia"
}

### delete post
DELETE localhost:8888/post/15
Content-Type: application/json

{
}


### get all posts
GET localhost:8888/post/all
Content-Type: application/json
