### register
POST localhost:8888/user
Content-Type: application/json

{
  "email" : "marto4@abv.bg",
  "password" : "m1235",
  "confirmPassword": "m1235",
  "firstName": "Marto",
  "lastName": "Ivanov",
  "phoneNumber": "0812311235",
  "isWorkman": true
}

### login
POST localhost:8888/login
Content-Type: application/json

{
  "email" : "marto2@abv.bg",
  "password" : "m1235"
}

### logout
POST localhost:8888/logout
Content-Type: application/json


### get all
GET localhost:8888/user/all
Content-Type: application/json

### add category
POST localhost:8888/user/category/21
Content-Type: application/json

{
"categoryName" : "boyadzhia"
}

