### register
POST localhost:8888/user
Content-Type: application/json

{
  "email" : "tsetso123@gmail.com",
  "password" : "asdf123",
  "confirmPassword": "asdf123",
  "firstName": "t",
  "lastName": "ta",
  "phoneNumber": "08123122235",
  "isWorkman": true
}

### login
POST localhost:8888/login
Content-Type: application/json

{
  "email" : "tsetso123@gmail.com",
  "password" : "asdf123"
}
### get all
GET localhost:8888/user/all
Content-Type: application/json

### add category
POST localhost:8888/user/category/21
Content-Type: application/json

{
"categoryName" : "boyadzhia"
}